#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPK_WEB_MVC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="prjTRK")]
	public partial class DBprjDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertManliCard(ManliCard instance);
    partial void UpdateManliCard(ManliCard instance);
    partial void DeleteManliCard(ManliCard instance);
    #endregion
		
		public DBprjDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["prjTRKConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBprjDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBprjDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBprjDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBprjDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ManliCard> ManliCard
		{
			get
			{
				return this.GetTable<ManliCard>();
			}
		}
		
		public System.Data.Linq.Table<ViewCompanies_Shopping> ViewCompanies_Shopping
		{
			get
			{
				return this.GetTable<ViewCompanies_Shopping>();
			}
		}
		
		public System.Data.Linq.Table<View_Company_CounterAll> View_Company_CounterAll
		{
			get
			{
				return this.GetTable<View_Company_CounterAll>();
			}
		}
		
		public System.Data.Linq.Table<ViewNews> ViewNews
		{
			get
			{
				return this.GetTable<ViewNews>();
			}
		}
		
		public System.Data.Linq.Table<ViewPromotions> ViewPromotions
		{
			get
			{
				return this.GetTable<ViewPromotions>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManliCard")]
	public partial class ManliCard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cardNumber;
		
		private string _cardPoint;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncardNumberChanging(int value);
    partial void OncardNumberChanged();
    partial void OncardPointChanging(string value);
    partial void OncardPointChanged();
    #endregion
		
		public ManliCard()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardNumber", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cardNumber
		{
			get
			{
				return this._cardNumber;
			}
			set
			{
				if ((this._cardNumber != value))
				{
					this.OncardNumberChanging(value);
					this.SendPropertyChanging();
					this._cardNumber = value;
					this.SendPropertyChanged("cardNumber");
					this.OncardNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardPoint", DbType="NVarChar(20)")]
		public string cardPoint
		{
			get
			{
				return this._cardPoint;
			}
			set
			{
				if ((this._cardPoint != value))
				{
					this.OncardPointChanging(value);
					this.SendPropertyChanging();
					this._cardPoint = value;
					this.SendPropertyChanged("cardPoint");
					this.OncardPointChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewCompanies_Shopping")]
	public partial class ViewCompanies_Shopping
	{
		
		private string _設施種類;
		
		private string _廠商ID;
		
		private string _廠商;
		
		private string _負責人;
		
		private string _電話;
		
		private string _建築物;
		
		private int _樓層;
		
		private int _櫃位;
		
		private string _簡介;
		
		private string _商標圖片;
		
		private string _位置圖;
		
		private string _實景圖;
		
		public ViewCompanies_Shopping()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_設施種類", DbType="NVarChar(50)")]
		public string 設施種類
		{
			get
			{
				return this._設施種類;
			}
			set
			{
				if ((this._設施種類 != value))
				{
					this._設施種類 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_廠商ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string 廠商ID
		{
			get
			{
				return this._廠商ID;
			}
			set
			{
				if ((this._廠商ID != value))
				{
					this._廠商ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_廠商", DbType="NVarChar(50)")]
		public string 廠商
		{
			get
			{
				return this._廠商;
			}
			set
			{
				if ((this._廠商 != value))
				{
					this._廠商 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_負責人", DbType="NVarChar(20)")]
		public string 負責人
		{
			get
			{
				return this._負責人;
			}
			set
			{
				if ((this._負責人 != value))
				{
					this._負責人 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_電話", DbType="NVarChar(20)")]
		public string 電話
		{
			get
			{
				return this._電話;
			}
			set
			{
				if ((this._電話 != value))
				{
					this._電話 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_建築物", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string 建築物
		{
			get
			{
				return this._建築物;
			}
			set
			{
				if ((this._建築物 != value))
				{
					this._建築物 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_樓層", DbType="Int NOT NULL")]
		public int 樓層
		{
			get
			{
				return this._樓層;
			}
			set
			{
				if ((this._樓層 != value))
				{
					this._樓層 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_櫃位", DbType="Int NOT NULL")]
		public int 櫃位
		{
			get
			{
				return this._櫃位;
			}
			set
			{
				if ((this._櫃位 != value))
				{
					this._櫃位 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_簡介", DbType="NVarChar(MAX)")]
		public string 簡介
		{
			get
			{
				return this._簡介;
			}
			set
			{
				if ((this._簡介 != value))
				{
					this._簡介 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_商標圖片", DbType="NVarChar(50)")]
		public string 商標圖片
		{
			get
			{
				return this._商標圖片;
			}
			set
			{
				if ((this._商標圖片 != value))
				{
					this._商標圖片 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_位置圖", DbType="NVarChar(50)")]
		public string 位置圖
		{
			get
			{
				return this._位置圖;
			}
			set
			{
				if ((this._位置圖 != value))
				{
					this._位置圖 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_實景圖", DbType="NVarChar(50)")]
		public string 實景圖
		{
			get
			{
				return this._實景圖;
			}
			set
			{
				if ((this._實景圖 != value))
				{
					this._實景圖 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Company_CounterAll")]
	public partial class View_Company_CounterAll
	{
		
		private string _廠商編號;
		
		private string _廠商名稱;
		
		private string _負責人;
		
		private string _建築物;
		
		private int _樓層;
		
		private string _電話;
		
		private string _位置;
		
		private string _簡介;
		
		private string _廠商圖示;
		
		private string _位置圖;
		
		public View_Company_CounterAll()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_廠商編號", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string 廠商編號
		{
			get
			{
				return this._廠商編號;
			}
			set
			{
				if ((this._廠商編號 != value))
				{
					this._廠商編號 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_廠商名稱", DbType="NVarChar(50)")]
		public string 廠商名稱
		{
			get
			{
				return this._廠商名稱;
			}
			set
			{
				if ((this._廠商名稱 != value))
				{
					this._廠商名稱 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_負責人", DbType="NVarChar(20)")]
		public string 負責人
		{
			get
			{
				return this._負責人;
			}
			set
			{
				if ((this._負責人 != value))
				{
					this._負責人 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_建築物", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string 建築物
		{
			get
			{
				return this._建築物;
			}
			set
			{
				if ((this._建築物 != value))
				{
					this._建築物 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_樓層", DbType="Int NOT NULL")]
		public int 樓層
		{
			get
			{
				return this._樓層;
			}
			set
			{
				if ((this._樓層 != value))
				{
					this._樓層 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_電話", DbType="NVarChar(20)")]
		public string 電話
		{
			get
			{
				return this._電話;
			}
			set
			{
				if ((this._電話 != value))
				{
					this._電話 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_位置", DbType="NVarChar(100)")]
		public string 位置
		{
			get
			{
				return this._位置;
			}
			set
			{
				if ((this._位置 != value))
				{
					this._位置 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_簡介", DbType="NVarChar(MAX)")]
		public string 簡介
		{
			get
			{
				return this._簡介;
			}
			set
			{
				if ((this._簡介 != value))
				{
					this._簡介 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_廠商圖示", DbType="NVarChar(50)")]
		public string 廠商圖示
		{
			get
			{
				return this._廠商圖示;
			}
			set
			{
				if ((this._廠商圖示 != value))
				{
					this._廠商圖示 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_位置圖", DbType="NVarChar(50)")]
		public string 位置圖
		{
			get
			{
				return this._位置圖;
			}
			set
			{
				if ((this._位置圖 != value))
				{
					this._位置圖 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewNews")]
	public partial class ViewNews
	{
		
		private int _活動ID;
		
		private string _廠商;
		
		private string _標題;
		
		private string _內容;
		
		private string _位址;
		
		private string _開始日期;
		
		private string _結束日期;
		
		private System.Nullable<System.DateTime> _發布日期;
		
		private string _分類;
		
		private string _圖片路徑;
		
		public ViewNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_活動ID", DbType="Int NOT NULL")]
		public int 活動ID
		{
			get
			{
				return this._活動ID;
			}
			set
			{
				if ((this._活動ID != value))
				{
					this._活動ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_廠商", DbType="NVarChar(50)")]
		public string 廠商
		{
			get
			{
				return this._廠商;
			}
			set
			{
				if ((this._廠商 != value))
				{
					this._廠商 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_標題", DbType="NVarChar(MAX)")]
		public string 標題
		{
			get
			{
				return this._標題;
			}
			set
			{
				if ((this._標題 != value))
				{
					this._標題 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_內容", DbType="NVarChar(MAX)")]
		public string 內容
		{
			get
			{
				return this._內容;
			}
			set
			{
				if ((this._內容 != value))
				{
					this._內容 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_位址", DbType="NVarChar(100)")]
		public string 位址
		{
			get
			{
				return this._位址;
			}
			set
			{
				if ((this._位址 != value))
				{
					this._位址 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_開始日期", DbType="VarChar(100)")]
		public string 開始日期
		{
			get
			{
				return this._開始日期;
			}
			set
			{
				if ((this._開始日期 != value))
				{
					this._開始日期 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_結束日期", DbType="VarChar(100)")]
		public string 結束日期
		{
			get
			{
				return this._結束日期;
			}
			set
			{
				if ((this._結束日期 != value))
				{
					this._結束日期 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_發布日期", DbType="DateTime")]
		public System.Nullable<System.DateTime> 發布日期
		{
			get
			{
				return this._發布日期;
			}
			set
			{
				if ((this._發布日期 != value))
				{
					this._發布日期 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_分類", DbType="NVarChar(20)")]
		public string 分類
		{
			get
			{
				return this._分類;
			}
			set
			{
				if ((this._分類 != value))
				{
					this._分類 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_圖片路徑", DbType="NVarChar(50)")]
		public string 圖片路徑
		{
			get
			{
				return this._圖片路徑;
			}
			set
			{
				if ((this._圖片路徑 != value))
				{
					this._圖片路徑 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewPromotions")]
	public partial class ViewPromotions
	{
		
		private int _活動ID;
		
		private string _廠商;
		
		private string _標題;
		
		private string _內容;
		
		private string _位址;
		
		private string _開始日期;
		
		private string _結束日期;
		
		private System.Nullable<System.DateTime> _發布日期;
		
		private string _分類;
		
		private string _圖片路徑;
		
		public ViewPromotions()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_活動ID", DbType="Int NOT NULL")]
		public int 活動ID
		{
			get
			{
				return this._活動ID;
			}
			set
			{
				if ((this._活動ID != value))
				{
					this._活動ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_廠商", DbType="NVarChar(50)")]
		public string 廠商
		{
			get
			{
				return this._廠商;
			}
			set
			{
				if ((this._廠商 != value))
				{
					this._廠商 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_標題", DbType="NVarChar(MAX)")]
		public string 標題
		{
			get
			{
				return this._標題;
			}
			set
			{
				if ((this._標題 != value))
				{
					this._標題 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_內容", DbType="NVarChar(MAX)")]
		public string 內容
		{
			get
			{
				return this._內容;
			}
			set
			{
				if ((this._內容 != value))
				{
					this._內容 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_位址", DbType="NVarChar(100)")]
		public string 位址
		{
			get
			{
				return this._位址;
			}
			set
			{
				if ((this._位址 != value))
				{
					this._位址 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_開始日期", DbType="VarChar(100)")]
		public string 開始日期
		{
			get
			{
				return this._開始日期;
			}
			set
			{
				if ((this._開始日期 != value))
				{
					this._開始日期 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_結束日期", DbType="VarChar(100)")]
		public string 結束日期
		{
			get
			{
				return this._結束日期;
			}
			set
			{
				if ((this._結束日期 != value))
				{
					this._結束日期 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_發布日期", DbType="DateTime")]
		public System.Nullable<System.DateTime> 發布日期
		{
			get
			{
				return this._發布日期;
			}
			set
			{
				if ((this._發布日期 != value))
				{
					this._發布日期 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_分類", DbType="NVarChar(20)")]
		public string 分類
		{
			get
			{
				return this._分類;
			}
			set
			{
				if ((this._分類 != value))
				{
					this._分類 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_圖片路徑", DbType="NVarChar(50)")]
		public string 圖片路徑
		{
			get
			{
				return this._圖片路徑;
			}
			set
			{
				if ((this._圖片路徑 != value))
				{
					this._圖片路徑 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
